version: "3.8"

services:
# frontend network for proxy server
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./www:/var/www