version: "3.8"

services:
# frontend network for proxy server
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - 15070:80
    restart: unless-stopped
    volumes:
      - ./srv1:/etc/nginx/conf.d
      - ./www:/var/www
      - /var/log/nginx/:/var/log/nginx
    logging:
      options:
        max-size: 5k